name: CI/CD

on:
# Khi push request được tạo trên nhánh master, workflow này sẽ được kích hoạt
  push:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        node-version: 20

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
        cache-dependency-path: football_management/api/package-lock.json

    - run: npm ci
    - run: npm run lint
    - run: npm run build
    - run: npm test
    

    env:
      Solution_Name: Football_Management
